### ISSUE TITLE
Codeplug file format documentation?

### ISSUE THREAD

**Issue by kg4zow** [DaleFarnsworth/codeplug#25]
Do you happen to have any documentation about the file format, i.e. how and where the contacts, zones, and channels are stored within the codeplug files for the various radios?

An example of what I'm asking about is https://kg4zow.us/dj296/memory.utf8.txt which I did for an Alinco 220 HT many years ago.

**Comment by DaleFarnsworth** [comment]
Here is the info that I initially used:
https://www.iz2uuf.net/wp/index.php/2016/06/04/tytera-dm380-codeplug-binary-format/

I have since found some more fields, but I haven't documented them in a
human readable format.  The information is contained here:
https://github.com/DaleFarnsworth/codeplug/blob/master/codeplug/codeplugs.json

It wouldn't be too difficult to write a program using that to create
human-readable documentation.

**Comment by DaleFarnsworth** [comment]
I'll close this now, but if you feel it's important for me to write such a program, please reopen this issue.

**Comment by DaleFarnsworth** [comment]
I've decided a human-readable documentation for the codeplugs is useful.  I'll write a program to produce one for each supported radio from the json codeplug description file.

**Comment by DaleFarnsworth** [comment]
I wrote a program to make the data in the json file more readable.  You can see the list of codeplug descriptions at the main README for this repository.
