### ISSUE TITLE
Import errors

### ISSUE THREAD

**Issue by NeuerUser** [DaleFarnsworth/codeplug#5]
Tested versions: 0.9.8, 10.0.0, 10.0.9.

When trying to export and reimport a codeplug, either as a text or as a spreadsheet, I always get the following error message:
"ScanLists.PriorityChannel1: bad record name '+ Soloth 2-9'
ScanLists.PriorityChannel2: bad record name '+ Soloth 2-9'
ScanLists.PriorityChannel1: bad record name '+ Soloth 2-9'
ScanLists.PriorityChannel2: bad record name '+ Soloth 2-9'
ScanLists.PriorityChannel1: bad record name '+ Soloth 2-9'
ScanLists.PriorityChannel2: bad record name '+ Soloth 2-9'
ScanLists.PriorityChannel1: bad record name '+ Soloth 2-9'
ScanLists.PriorityChannel2: bad record name '+ Soloth 2-9'
ScanLists.PriorityChannel1: bad record name '+ Soloth 2-9'
ScanLists.PriorityChannel2: bad record name '+ Soloth 2-9'
ScanLists.PriorityChannel1: bad record name '+ Soloth 2-9'
ScanLists.PriorityChannel2: bad record name '+ Soloth 2-9'"

I thought it could be the "+", but exchanging it to some letter did not help.

I used this codeplug (but also tested others):
http://ham-dmr.ch/wp-content/uploads/2015/09/MD-380-FREE_2016-12-06.zip

**Comment by DaleFarnsworth** [comment]
Thank you very much for reporting this problem.  It is fixed in v0.10.11.

Note that there will still be some warning messages when you open the rdt file with editcp. These warnings are correct. The values of the Priority Channel 1 and Priority Channel 2 fields in several of the scan lists are invalid.  If you open the same rdt file in the Tytera CPS program and examine those scan lists, you will see a blank value for the Priority Channel fields, indicating that the value in the rdt file is invalid.

Thanks again.
Closing.

**Comment by NeuerUser** [comment]
Thanks a lot. It seems to work now. Great program, by the way. Thanks really for your hard work!

73 de HB9TZX
