### ISSUE TITLE
Error message when switching RX Group list entry

### ISSUE THREAD

**Issue by NeuerUser** [DaleFarnsworth/codeplug#6]
Tested version: 0.10.11

With the same codeplug as my last issue (http://ham-dmr.ch/wp-content/uploads/2015/09/MD-380-FREE_2016-12-06.zip), I have the problem that I cannot change the RX group setting for a channel in the channel configuration dialog. E.g. I want to change the setting from "DMR+" to "BM / M", I get the following error message:

"RX Group List bad list record name 'BM / M'"

**Comment by DaleFarnsworth** [comment]
The problem was that the RX Group List name in the codeplug has a trailing space character: 'BM / M ' and I didn't handle this correctly.  I now permit trailing spaces on names when they are loaded from an existing codeplug, and only remove trailing spaces when new names are entered via the GUI.

Fixed in v0.10.12.

Thank you for reporting this problem.

Closing.
